apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rudovik-tk-tls
spec:
  secretName: rudovik-tk
  dnsNames:
    - rudovik.tk
    - www.rudovik.tk
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
    group: cert-manager.io
