apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-multi-com-tls
spec:
  secretName: rudovik-tk
  issuerRef: letsencrypt-prod
  kind: ClusterIssuer
commonName: rudovik.tk
dnsNames:
  - rudovik.tk
  - www.rudovik.tk
acme:
  config:
    - http01:
        ingressClass: nginx
      domains:
        - rudovik.tk
        - www.rudovik.tk
